language: python
python:
  - 3.5
branches:
  only:
    - master

services:
  - docker
sudo: required

before_install:
  - docker-compose -f .travis/docker-compose-travis.yml up -d

install:
    - pip install -r requirements/travis.txt

script:
  - docker exec -t -e TRAVIS=1 analytics_api_testing bash -c "
      cd /edx/app/analytics_api/analytics_api/ &&
      make $TARGETS
      "

matrix:
  include:
    - env:
        TESTNAME=quality
        TARGETS="quality"
    - env:
        TESTNAME=test-python
        TARGETS="test"
      after_success:
        - docker exec analytics_api_testing /edx/app/analytics_api/analytics_api/.travis/run_coverage.sh
        - codecov --disable pycov
    - env:
        TESTNAME=test-python-django20
        TARGETS="DJANGO_VERSION=django20 test"
    - env:
        TESTNAME=test-python-django21
        TARGETS="DJANGO_VERSION=django21 test"
    - env:
        TESTNAME=test-python-django22
        TARGETS="DJANGO_VERSION=django22 test"
