language: python

branches:
  only:
    - master

services:
  - docker
sudo: required

before_install:
  - docker-compose -f .travis/docker-compose-travis.yml up -d

install:
  # Installation of packages is broken if python-yaml ubuntu package
  # is installed in the container
  #  - docker exec -t analytics_api_testing bash -c "
  #     apt remove python-yaml -y
  # "
  - docker exec -t analytics_api_testing bash -c "
      cd /edx/app/analytics_api/analytics_api/ &&
        pip install -r requirements/travis.txt
    "

script:
  - docker exec -t -e TRAVIS=1 analytics_api_testing bash -c "
      cd /edx/app/analytics_api/analytics_api/ &&
      make $TARGETS
      "
matrix:
  include:
    - python: 2.7
      env:
        TESTNAME=quality
        TARGETS="quality"
    - python: 2.7
      env:
        TESTNAME=test-python
        TARGETS="test"
      after_success:
        - pip install -U codecov
        - docker exec analytics_api_testing /edx/app/analytics_api/analytics_api/.travis/run_coverage.sh
        - codecov
    - python: 3.5
      env:
        TESTNAME=quality-python-3.5
        TARGETS="PYTHON_ENV=py35 quality"
    - python: 3.5
      env:
        TESTNAME=test-python-3.5
        TARGETS="PYTHON_ENV=py35 test"
  allow_failures:
    - env: TESTNAME=quality-python-3.5
    - env: TESTNAME=test-python-3.5


